apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgallery-backend
  namespace: eventgallery  # Ensure the namespace exists or create it
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventgallery-backend
  template:
    metadata:
      labels:
        app: eventgallery-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/noluchs/sem4-eventgallery/eventgallery-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef: 
                name: eventgallery-backend-secrets  # Reference secrets for sensitive data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:  # Ensures the pod is ready before receiving traffic
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:  # Ensures the container is restarted if unhealthy
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20