apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgallery-frontend
  namespace: eventgallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventgallery-frontend
  template:
    metadata:
      labels:
        app: eventgallery-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/noluchs/sem4-eventgallery/eventgallery-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://eventgallery-backend:5000"