#cloud-config

packages:
  - curl
  - sudo
  - jq
  - openssh-client

write_files:
  # This key is well known and only for educational purposes
  - path: /opt/id_lerncloud
    permissions: '0600'
    encoding: b64
    content: |
      LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMUI2SmRaZ2J6K1RjSHR3YzI2YXVCckIwMHNQZXFZVnkyZHUyajRrWGE4NFowTm96Ckx1SkVvTC9jUmJKNldZQWJFR3ZPQklYU1VER2MvQkRucm9iMkxpYlpvUUZjd0x6WTQwV3BQbTZjU3ozVnBhTWQKYVN5VTdvWENLbjAwMG53V0NXQWV2RlVRRnlkdmFIRUFlNnArMmc0K2dyc043UFNNbDZHaW9jbStKK3lQTWlONgo5Rk45RFFIREk4cjFkeTJEbDhmeVVHMS9qNDFiQ1RNNmRqWmF3dTdKOC9JSEVpc1ZMUy8zaGRJUGxwd3UrWXJvClFXeW16VDYrMEQveUxSMmdJZlU3K1d0NXNnU3pXVU9la29KMGdvSmt0QkZGWGpEYkR2RjJtaXE5aDlzZWVmZGkKQ0tNKzJFY2krTUpUcG85K1cwS0hNSFdvWFRnaFNPNTAvWDYrbndJREFRQUJBb0lCQUZXa0xxT0gwbExSZC80TgpxS2tXVnRUa2tZWTNCc015MmZnVHVWV2lhQTVpbkJHeXgwOTZrM0xEZzgrd0M2M3ZCdjVPU0ZPVEpDSzBwVWt3CkdocGc2eXdmQzJieUFkemZZa0lBY2lCKzBDT2d4NDJrbWM5STdLaVE0Si8vQlVDbVVNOWdPNGlXWDNTNXUwVlQKdW5vemtCdkIvSU1UdXIrY3pOYTdyOG5haGlmZm9wRnJBOGFxUTN5TnlxcVFxUzlxK0xuSFpUbXRBaXNLR0pDUAp4U2JRVGFrelhZMDZGN2NEek9nTkdRcU11aUc1ZGErekJWR0NrcThVQzJXUmR1RmdMSkhZOXFkZzN4azVxWkZWClNwcTNqbkRza28rSUczcklIK3B4MG5USmhjMEg1MHZ6aGR5Q1NucVVINlZ6cEJYYTEyYnhOcjY0WHpQdmFDYWUKWStOSHNNRUNnWUVBN0JlVCtnSXI4RjhKelZKMDdTQkR4QlpqSHlISk1RaDNjbGttR3VYTHdGQVppa2w5TGZGaQpGaEJJTlVPSW5ObjNXai9TNTBCS0E1R0hUQUdhUkowMEtqWDZ1Vmw2dUU5YUJYUHJ1dGVFazdhTXBFZU1sczc5ClpiY0ZQTTFxQjl1Qk5GYXJnSlNOc3UwQ04xWTA5anAzeHdDTTFMRERnSk9jUTFGb3Yxc3NwRmNDZ1lFQTVnRjMKdXZyRHpJdSsyTUFvNlM5d0NSRVY0d0FHaDFhMVIzQW5pZXpiUVJOdGdaclRPbWl4dlJlZmF3aGY3Ujc3L1NmYQpGclcvdC8vSVlBV3JqbGV3cTBUNU9uSXpwTVFSS3htUGdJRDFxWnNoVlM5MmN5cHVJOXJ4b3BMdmJ5TWt2TnhCCk9IMUJLOUdXQTVNeCtzTDcvck1pRkZVMlFpT2phYWR0ZFlma2l2a0NnWUFscTZsdjFkTGUrcnNjcU5DQldZbVcKaXgvcndyOVFkSkppaTNqNkI3cVlCKy9iVWRpSWNTQitkc0NleHhUUU9qTXVra3A3blpWeHRsSEpQZVE0bUlEUApUMmVmRlhqd1diRDZkOEdnUVcwbENKYXVTOEJSKzlzUTFNQWdNSUovbUhXb1BVQUdOeTNZNDlwYnJBU3RXU3p0CmN0Z0Z3K0tkN0crZGlpclZoWjI4NXdLQmdBSkJzMjRITmRLVThHdHAvenpDZFdQeFlmaVhNSGsxZFpQYzJ0WjAKbDNZYy9hOE8yTkd5NDBPS3JzcTdDMDNsUnUybDdYTFpsNmJ6Z0lESXJYVTVFUWV0SnBEWFBBQjYxL3hIUk93cQoxNzR4UW5OMmdzQUFnNUlnZk14dWlxRFpoR3ZCOFhYZmJMdEVWQ2QyMHorMW1BbFlzcFhtZkNETC9yZHpxQlJHCklBenBBb0dCQUpQRThTQWFacG13ZGo4RWZONUo5L3BPN3dRUUJxVWVnVktZRGxrMG1xRlh0US9VZzJmYlg1VmcKWVN2dHpKTUN6ZDFOcWt3eTVSSTZQaS9JVFNwQ3BWSUpGWWxLamtwdm9LQzZObXlURW45bjU4Wkw5VjhNbk1jOAo3OEdYcEZNOGtrVVp4RGQwRHkxREt2bW5DSEJDR2EvVGdUK1pUNUtvL2xBUlBNenBqVWVmCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

  # Systemd service for GitHub Runner
  - path: /etc/systemd/system/github-runner.service
    permissions: '0644'
    content: |
      [Unit]
      Description=GitHub Runner
      After=network.target

      [Service]
      ExecStart=/opt/github-runner/svc.sh start
      ExecStop=/opt/github-runner/svc.sh stop
      User=ubuntu
      WorkingDirectory=/opt/github-runner
      Restart=always

      [Install]
      WantedBy=multi-user.target

  .
      ...

runcmd:
  # Ensure network is up
  - while ! ping -c 1 -W 1 8.8.8.8; do echo "Waiting for network..." >> /var/log/cloud-init-debug.log; sleep 1; done
  - echo "Network is up" >> /var/log/cloud-init-debug.log

  # Download k0sctl and apply configuration
  - curl -sSLf https://github.com/k0sproject/k0sctl/releases/latest/download/k0sctl-linux-amd64 -o /usr/local/bin/k0sctl >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to download k0sctl" >> /var/log/cloud-init-debug.log; exit 1; }
  - sudo chmod +x /usr/local/bin/k0sctl >> /var/log/cloud-init-debug.log 2>&1
  - sudo k0sctl apply --config /opt/k0s.yaml >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to apply k0s configuration" >> /var/log/cloud-init-debug.log; exit 1; }
  - cdopt/k0s.yaml > /opt/kubeconfig >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to export kubeconfig" >> /var/log/cloud-init-debug.log; exit 1; }
  - echo "k0s cluster setup complete" >> /var/log/cloud-init-debug.log

  # Github Runner
  - echo "Starting GitHub Runner setup" >> /var/log/cloud-init-debug.log

  # Erstelle den Ordner und setze Berechtigungen
  - mkdir -p /opt/github-runner
  - chown ubuntu:ubuntu /opt/github-runner
  - chmod 755 /opt/github-runner

  # Lade und entpacke den GitHub Runner
  - cd /opt/github-runner
  - curl -o actions-runner.tar.gz -L https://github.com/actions/runner/releases/download/v2.303.0/actions-runner-linux-x64-2.303.0.tar.gz >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to download GitHub Runner" >> /var/log/cloud-init-debug.log; exit 1; }
  - tar xzf ./actions-runner.tar.gz >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to extract GitHub Runner" >> /var/log/cloud-init-debug.log; exit 1; }
  - rm ./actions-runner.tar.gz

  # Setze die Dateiberechtigungen
  - chown -R ubuntu:ubuntu /opt/github-runner
  - chmod -R 755 /opt/github-runner

  # Konfiguriere den GitHub Runner als Benutzer `ubuntu`
  - sudo -u ubuntu ./config.sh --unattended --url https://github.com/${github_org}/${github_repo} --token ${github_token} >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to configure GitHub Runner" >> /var/log/cloud-init-debug.log; exit 1; }

  # Installiere und starte den Dienst als Benutzer `ubuntu`
  - sudo ./svc.sh install >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to install GitHub Runner service" >> /var/log/cloud-init-debug.log; exit 1; }
  - systemctl daemon-reload >> /var/log/cloud-init-debug.log 2>&1
  - systemctl enable github-runner >> /var/log/cloud-init-debug.log 2>&1
  - systemctl start github-runner >> /var/log/cloud-init-debug.log 2>&1 || { echo "Failed to start GitHub Runner service" >> /var/log/cloud-init-debug.log; exit 1; }
  - echo "GitHub Runner setup complete" >> /var/log/cloud-init-debug.log